apiVersion: v1
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.17.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "my-nginx2_as3",
            "remark": "user define configmap ",
            "my-nginx2-as3": {
                "class": "Tenant",
                "my-nginx2-80": {
                    "class": "Application",
                    "template": "generic",
                    "my-nginx-80-vs": {
                        "class": "Service_HTTP",
                        "remark": "my-nginx-prod-vip",
                        "virtualAddresses": [
                            "10.192.75.113"
                        ],
                        "virtualPort": 80,
                        "snat": {
                            "bigip": "/Common/SNAT-VLAN"
                        },
                        "profileHTTP": {
                            "bigip": "/Common/http-custom-xff"
                        },
                        "profileTCP": {
                            "ingress": {
                                "bigip": "/Common/f5-tcp-wan"
                            },
                            "egress": {
                                "bigip": "/Common/f5-tcp-lan"
                            }
                        },
                        "pool": "my-nginx-pool",
                        "persistenceMethods": [],
                        "profileMultiplex": "basic"
                    },
                    "my-nginx-pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "my-nginx-443-vs": {
                        "class": "Service_HTTPS",
                        "remark": "my-nginx-prod-ssl-vip",
                        "virtualAddresses": [
                            "10.192.75.113"
                        ],
                        "virtualPort": 443,
                        "redirect80": false,
                        "snat": {
                            "bigip": "/Common/SNAT-VLAN"
                        },
                        "profileHTTP": {
                            "bigip": "/Common/http-custom-xff"
                        },
                        "profileTCP": {
                            "ingress": {
                                "bigip": "/Common/f5-tcp-wan"
                            },
                            "egress": {
                                "bigip": "/Common/f5-tcp-lan"
                            }
                        },
                        "pool": "my-nginx-pool",
                        "persistenceMethods": [],
                        "profileMultiplex": "basic",
                        "serverTLS": {
                            "bigip": "/Common/clientssl"
                        }
                    }
                }
            }
        }
    }
kind: ConfigMap
metadata:
  labels:
    as3: "true"
    f5type: virtual-server
  name: my-nginx-vs
  namespace: my-nginx2