apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: demo-staging
  namespace: demo-domains
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - mysite.f5demo.com