apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  generation: 1
  labels:
    f5cr: "true"
  name: demo-staging
  namespace: demo-domains
spec:
  host: mysite.f5demo.com
  httpTraffic: allow
  pools:
  - nodeMemberLabel: node-role.kubernetes.io/worker=true
    path: /
    service: demo-staging-mysite
    servicePort: 8080
  tlsProfileName: demo-staging
  virtualServerAddress: 10.192.75.113
status:
  status: Ok
  vsAddress: None