apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-myapp
  labels:
    f5cr: "true"
spec:
  host: myapp.f5demo.com
  virtualServerAddress: "10.192.75.111"
  hostGroup: "f5demo"
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /myapp
    service: f5-demo
    servicePort: 8080