apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-demo-cafe
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerHTTPSPort: 80
  snat: auto
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: nginx-ingress
    servicePort: 80