kind: ConfigMap
apiVersion: v1
metadata:
  name: my-nginx-vs
  namespace: my-nginx2
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.17.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "my-nginx2_as3",
            "remark": "my-nginx2_as3",
            "my-nginx2_as3": {
                "class": "Tenant"
            }
        }
    }