apiVersion: v1
data:
  template: |
    {
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.17.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "my-nginx2_as3",
        "remark": "user define configmap "
        }
    }
kind: ConfigMap
metadata:
  labels:
    as3: "true"
    f5type: virtual-server
  name: my-nginx-vs
  namespace: my-nginx2