apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-hello-world
  labels:
    f5cr: "true"
spec:
  host: mysite.f5demo.com
  tlsProfileName: reencrypt-tls
  virtualServerAddress: "10.192.75.106"
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: f5-hello-world
    servicePort: 8080