apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-myapp
  labels:
    f5cr: "true"
spec:
  domainName: f5demo.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: myapp.f5demo.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/k8s19-cluster
    monitor:
      type: http
      send: "GET /"
      recv: ""
      interval: 10
      timeout: 10