apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-frappuccino
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: frappuccino.example.com
  hostGroup: "cafe"
  virtualServerAddress: "10.192.75.117"
  virtualServerHTTPSPort: 443
  tlsProfileName: reencrypt-frappuccino
  httpTraffic: redirect
  snat: auto
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: "GET /frappuccino HTTP/1.1\r\nHost: frappuccino.example.com\r\n"
      timeout: 10
      type: https
    path: /frappuccino
    service: nginx-ingress
    servicePort: 443