apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: securework-virtual
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.192.75.110"
  virtualServerHTTPSPort: 443
  httpTraffic: redirect
  waf: /Common/WAF_POLICY
  tlsProfileName: reencrypt-tls
  host: portal.securework.com
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 443