apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-mysite
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.192.75.111"
  virtualServerHTTPSPort: 443
  httpTraffic: redirect
  tlsProfileName: reencrypt-tls
  host: mysite.f5demo.com
  pools:
  - path: /
    service: f5-demo
    servicePort: 443