apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  type: deployment
  nginxPlus: false
  image:
    repository: nginx/nginx-ingress
    tag: 2.1.1-ubi
    pullPolicy: Always
  replicas: 1
  serviceType: ClusterIP