apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: svc1-tcp-transport-server
  namespace: default
spec:
  virtualServerAddress: "10.192.75.119"
  virtualServerPort: 80
  mode: standard
  snat: auto
  pool:
    service: f5-demo
    servicePort: 80
    monitor:
      type: tcp
      interval: 10
      timeout: 31