apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-mysite
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.192.75.111"
  virtualServerHTTPPort: 80
  policyName: policy-f5demo
  host: mysite.f5demo.com
  hostGroup: "f5demo"
  pools:
  - path: /
    service: f5-demo
    servicePort: 80