apiVersion: v1
kind: Service
metadata:
  name: f5-hello-world-03
  namespace: default
  labels:
    app: f5-hello-world
    cis.f5.com/as3-tenant: k8s_tenant3
    cis.f5.com/as3-app: A3
    cis.f5.com/as3-pool: web_pool
spec:
  ports:
  - name: f5-hello-world
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: f5-hello-world