apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual-definition
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: cafe.example.com
  virtualServerAddress: "10.192.75.110"
  virtualServerName: "K8S_iApp_004_test"
  virtualServerHTTPPort: 80
  pools:
  - path: /
    service: hello-world-app
    servicePort: 8080