apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual-definition
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.192.75.110"
  virtualServerName: "Virtual Server Definition"
  host: cafe.example.com
  pools:
  - path: /
    service: hello-world-app
    servicePort: 8080