apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-demo
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.106"
  host: mysite.f5demo.com
  pools:
  - path: /
    service: f5-demo
    servicePort: 80
  - path: /
    service: f5-demo
    servicePort: 443