
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
 name: f5-demo
 labels:
   f5cr: "true"
spec:
 virtualServerAddress: "10.192.75.111"
 virtualServerHTTPPort: 80
 pools:
 - path: /
   service: f5-demo
   servicePort: 80