apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-mysite
  labels:
    f5cr: "true"
spec:
  domainName: mysite.f5demo.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: mysite.f5demo.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/bip-ip-ve5-pme.lab.fp.f5net.com
    monitor:
      type: http
      send: "GET / HTTP/1.1\r\nHost: mysite.f5demo.com\r\nConnection: Close\r\n\r\n"
      recv: ""
      interval: 10
      timeout: 30