apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-hello
  namespace: default
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.121"
  virtualServerHTTPPort: 80
  snat: auto
  pools:
  - monitor:
      interval: 10
      recv: ""
      send: "GET /"
      timeout: 31
      type: http
    path: /
    service: hello-world-app
    servicePort: 8080