apiVersion: v1
data:
  data: |
    {
      "virtualServer": {
        "backend": {
        "serviceName": "f5nginx",
        "servicePort": 80
        },
        "frontend": {
          "partition": "k8s-be-qa-iz1-bs",
          "iapp": "/Common/K8S_iApp_004",
          "iappPoolMemberTable": {
            "name": "Pool_Definition__Pool_Members",
            "columns": [
              {"name": "Pool_Member_IP", "kind": "IPAddress"},
              {"name": "Pool_Member_Port", "kind": "Port"}
            ]
          },
          "iappOptions": {
            "description": "K8S_iApp_004 test"
          },
          "iappVariables": {
            "Virtual_Definition__VS_Type": "Standard",
            "Virtual_Definition__VS_IP": "10.90.32.99",
            "Virtual_Definition__VS_Port": "443",
            "Virtual_Definition__VS_TCP_Client_Profile": "/Common/tcp",
            "Virtual_Definition__VS_TCP_Server_Profile": "/#same_as_client#",
            "Virtual_Definition__VS_HTTP_Profile": "/Common/http",
            "Virtual_Definition__VS_SSL_Client_Profiles": "/Common/clientssl",
            "Virtual_Definition__VS_SSL_Server_Profiles": "/#none#", 
            "Virtual_Definition__VS_FastL4_Client_Profile": "/Common/fastL4",
            "Virtual_Definition__VS_VLANs_Enabled": "VLAN1384",
            "Virtual_Definition__VS_SNATPool": "/Common/de-kae-bs-poci-snat-be-qa",
            "Virtual_Definition__VS_Persistence": "/Common/source_addr",
            "Virtual_Definition__VS_iRules": "/#none#",            
            "Pool_Definition__Pool_Health_Monitors": "/Common/http",
            "Pool_Definition__Pool_Load_Balancing_Method": "least-connections-member"
          }
        }
      }
    }
  schema: f5schemadb://bigip-virtual-server_v0.1.3.json
kind: ConfigMap
metadata:
  labels:
    app: f5nginx
    f5type: virtual-server
  name: f5nginx​