apiVersion: "cis.f5.com/v1"
kind: IngessLink
metadata:
  name: my-ingresslink
  namespace: nginx-ingress
spec:
  virtualServerAddress: "10.192.75.110"
  iRules:
    - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-kic