apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  labels:
    app: f5-demo-coffee
    cis.f5.com/as3-tenant: Hello_World
    cis.f5.com/as3-app: Hello_World_app
    cis.f5.com/as3-pool: Hello_World_app_pool
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: hello-world-app
  type: ClusterIP