apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: ts-loadbalancingmethod
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.111"
  virtualServerPort: 80
  virtualServerName: "loadbalancingmethod-change"
  mode: standard
  snat: auto
  pool:
    service: hello-world-app
    servicePort: 8080
    loadBalancingMethod: least-connections-member
    monitor:
      type: tcp
      interval: 10
      timeout: 31