apiVersion: v1
kind: Service
metadata:
  name: f5-automation-config-converter-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: f5-automation-config-converter
  type: ClusterIP