apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/ipamLabel: Production
  labels:
    app: f5-demo-production
  name: f5-demo-production
  namespace: default
spec:
  ports:
  - name: f5-demo-production
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: f5-demo-production
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: