apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-loadbalancingmethod
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.110"
  virtualServerName: "loadbalancingmethod-change"
  virtualServerHTTPPort: 80
  pools:
  - path: /
    service: hello-world-app
    servicePort: 8080
    loadBalancingMethod: dynamic-ratio-member
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 31