---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-gss-server
  namespace: default
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.110"
  virtualServerName: "VS_crds"
  host: "mysite.f5demo.com"
  pools:
  - path: /service1
    service: svc-gss-server-lab1
    servicePort: 8080
  - path: /service2
    service: svc-gss-server-lab2
    servicePort: 8080
...


