kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-spinneker
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.30.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Spinnaker Template",
            "new-tenant": {
                "class": "Tenant",
                "new-application": {
                    "class": "Application",
                    "template": "generic",
                    "new-virtual": {
                        "class": "Service_TCP",
                        "remark": "spinnaker",
                        "virtualAddresses": [
                            "virtual IP"
                        ],
                        "pool": "spinnaker-pool"
                    },
                    "spinnaker-pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 900,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }