kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application",
            "app1": {
                "class": "Tenant",
                "helloworld": {
                    "class": "Application",
                    "template": "generic",
                    "helloworld_vs": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "192.168.2.160"
                        ],
                        "virtualPort": 80,
                        "remark": "ingress: better together demo app",
                        "pool": "helloworld_pool"
                    },
                    "helloworld_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }