apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: policy-mysite
  namespace: default
spec:
  l7Policies:
    waf: /Common/WAF_Policy
  ltmPolicies:
    type: /Common/Log all requests