apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: edge-tls
  namespace: default
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - cafe.example.com