apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: f5ipams.fic.f5.com
spec:
  group: fic.f5.com
  names:
    kind: F5IPAM
    plural: f5ipams
    shortNames:
      - ipm
    singular: f5ipam
  scope: Namespaced
  versions:
    -
      name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hostSpecs:
                  type: array
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                      cidr:
                        type: string
            status:
              type: object
              properties:
                IPStatus:
                  type: array
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                      ip:
                        type: string
                      cidr:
                        type: string
