apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: default
  labels:
    app: tea-svc
spec:
  ports:
  - name: tea-svc
    port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
  selector:
    app: tea
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: default
  labels:
    app: coffee-svc
spec:
  ports:
  - name: coffee-svc
    port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
  selector:
    app: coffee