apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: default
  labels:
    app: tea-svc
spec:
  ports:
  - name: tea-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: tea
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: default
  labels:
    app: coffee-svc
spec:
  ports:
  - name: coffee-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: coffee
---
apiVersion: v1
kind: Service
metadata:
  name: mocha-svc
  namespace: default
  labels:
    app: mocha-svc
spec:
  ports:
  - name: mocha-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: mocha