---
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver2
  namespace: echoserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver2
  template:
    metadata:
      labels:
        app: echoserver2
    spec:
      containers:
        - name: echoserver2
          image: f5devcentral/f5-hello-world:latest
          ports:
            - containerPort: 8080
              protocol: TCP