apiVersion: v1
kind: Service
metadata:
  name: echoserver2
  namespace: echoserver2
spec:
  selector:
    app: echoserver2
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort