apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-server
  namespace: kube-system
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: f5-server
  template:
    metadata:
      labels:
        app: f5-server
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      containers:
        - name: f5-server
          image: "vklohiya1/k8s-bigip-ctlr:2.7.0-1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/containers/latest/
              "--bigip-username=$(BIGIP_USERNAME)",
              "--bigip-password=$(BIGIP_PASSWORD)",
              "--bigip-url=192.168.200.60",
              "--bigip-partition=k8s",
              "--pool-member-type=cluster",
              "--flannel-name=fl-vxlan",
              "--log-level=DEBUG",
              "--insecure=true",
              "--custom-resource-mode=true",
              "--as3-validation=true",
              "--log-as3-response=true",
              "--ipam=true",
          ]
      serviceAccountName: bigip-ctlr