apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-two
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.110"
  virtualServerName: "K8S_iApp_004_test"
  virtualServerHTTPPort: 80
  policyName: policy-two
  persistenceProfile: source-address
  pools:
  - path: /
    service: hello-world-app
    servicePort: 8080
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10