apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: ts-persistence-policy
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.111"
  virtualServerPort: 80
  virtualServerName: "persistence-change"
  policyName: policy-persistence-tcp
  mode: standard
  snat: auto
  pool:
    service: hello-world-app
    servicePort: 8080
    monitor:
      type: tcp
      interval: 10
      timeout: 10