apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-hello-world
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.192.75.106"
  pools:
  - path: /
    service: f5-hello-world
    servicePort: 8080