kind: ConfigMap
apiVersion: v1
metadata:
  name: vs-configmap-hub-2
  namespace: control-hub-2
  labels:
    f5type: virtual-server
    as3: "true"
    hubMode: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210",
            "label": "http",
            "remark": "A2 Template",
            "control-hub-2": {
                "class": "Tenant",
                "A2": {
                    "class": "Application",
                    "template": "generic",
                    "a1_80_vs_n2": {
                        "class": "Service_HTTP",
                        "remark": "n2 namespace",
                        "virtualAddresses": [
                            "10.192.75.102"
                        ],
                        "pool": "web_pool_n2"
                    },
                    "web_pool_n2": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }