apiVersion: v1
kind: Service
metadata:
  name: f5-demo-service
  namespace: kubernetes-dashboard
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: f5-demo-deployment
  type: ClusterIP