apiVersion: v1
kind: Service
metadata:
  name: f5-demo-service
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: f5-demo-deployment
  type: ClusterIP