
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
 name: f5-demo-myapp
 labels:
   f5cr: "true"
spec:
 host: myapp.f5demo.com
 ipamLabel: Test
 pools:
 - path: /
   service: f5-demo
   servicePort: 80