apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-brew
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  domainName: brew.example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/east
    monitor:
      type: https
      send: "GET /brew HTTP/1.1\r\nHost: brew.example.com\r\n"
      recv: ""
      interval: 10
      timeout: 30