apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-chai
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  domainName: chai.example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/east
    monitor:
      type: https
      send: "GET /chai HTTP/1.1\r\nHost: chai.example.com\r\n"
      recv: ""
      interval: 10
      timeout: 30