---
apiVersion: v1
kind: Service
metadata:
  name: svc-gss-server-lab1
  namespace: default
  labels:
    app: gss-server-lab1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8085
  selector:
    app: gss-server-lab1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: svc-gss-server-lab2
  namespace: default
  labels:
    app: gss-server-lab2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8085
  selector:
    app: gss-server-lab2
  type: NodePort


