apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: coffee-virtual-server
  namespace: coffee
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.192.75.110"
  virtualServerHTTPPort: 80
  host: coffee.example.com
  pools:
  - path: /coffee
    service: f5-demo-coffee
    servicePort: 80