apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-cafe
  namespace: default
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - cafe.example.com