apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-coffee
  namespace: default
  labels:
    f5cr: "true"
spec:
  host: "*.example.com"
  virtualServerAddress: "10.192.75.117"
  snat: auto
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: f5-demo
    servicePort: 80