apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-http
  name: httpd-http
  namespace: f5-test-httpd
spec:
  clusterIP: 172.30.79.231
  clusterIPs:
  - 172.30.79.231
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    nodePort: 30846
    port: 80
  selector:
    app: httpd-http
  type: NodePort