apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: nginx-http-vs
  namespace: f5-test-nginx
spec:
  host: nginx-http.snamretegas.priv
  hostGroup: samevip
  httpTraffic: redirect
  pools:
  - monitor:
      interval: 5
      send: GET /rn
      type: http
    path: /
    service: nginx-http
    servicePort: 80
  serviceAddress:
  - arpEnabled: true
    icmpEcho: enable
    routeAdvertisement: all
    spanningEnabled: false
  tlsProfileName: nginx-edge-tls
  virtualServerAddress: 10.126.19.73
  virtualServerName: common