apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-cafe
  namespace: default
  labels:
    f5cr: "true"
spec:
  domainName: mysite.f5demo.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/k8s
    monitor:
    - interval: 10
      recv: ""
      send: "GET / HTTP/1.1\r\nHost: mysite.f5demo.com\r\n"
      timeout: 31
      type: http