apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: tea-virtual-server-443
  namespace: default
spec:
  virtualServerAddress: "10.192.75.110"
  virtualServerPort: 443
  virtualServerName: tea-virtual-server-443
  mode: standard
  snat: auto
  pool:
    service: f5-demo-tea
    servicePort: 443
    monitor:
      type: tcp
      interval: 10
      timeout: 10