apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: tea-virtual-server-80
  namespace: default
spec:
  virtualServerAddress: "10.192.75.110"
  virtualServerPort: 80
  virtualServerName: tea-virtual-server-80
  mode: standard
  snat: auto
  pool:
    service: f5-demo-tea
    servicePort: 80
    monitor:
      type: tcp
      interval: 10
      timeout: 10