apiVersion: v1
kind: Service
metadata:
  name: f5-demo
  labels:
    app: f5-demo
    cis.f5.com/as3-tenant: sensu-system_infs_tenant
    cis.f5.com/as3-app: Shared
    cis.f5.com/as3-pool: alertmanager-cluster_pool
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: f5-demo
  type: ClusterIP