apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata: 
  labels: 
    f5cr: "true"
  name: reencrypt-tls-mysite
spec: 
  hosts: 
    - mysite.f5demo.com
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip