apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-demo-2
  labels:
    f5cr: "true"
spec:
  host: myapp.f5demo.com
  virtualServerAddress: "10.192.75.111"
  virtualServerHTTPSPort: 443
  tlsProfileName: passthrough-tls-myapp
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: https
    path: /
    service: f5-demo
    servicePort: 443