apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: kubernetes-dashboard-certs
  namespace: kubernetes-dashboard
spec:
  hosts:
    - example.com
  tls:
    clientSSL: /Common/clientssl
    reference: bigip
    termination: edge
---
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: k8s-dashboard
  namespace: kubernetes-dashboard
spec:
  host: example.com
  pools:
    - monitor:
        interval: 15
        recv: ""
        send: "GET /oauth/health"
        timeout: 5
        type: http
    - path: /
      service: kubernetes-dashboard-proxy
      servicePort: 3000
  tlsProfileName: kubernetes-dashboard-certs
  httpTraffic: redirect
  virtualServerAddress: 10.192.75.121
  virtualServerHTTPSPort: 443
  #virtualServerName: k8s-dashboard