kind: ConfigMap
apiVersion: v1
metadata:
  name: policyFirewallEnforced
  namespace: cattle-system
  labels:
    f5type: virtual-server
    overrideAS3: "true"  # set to true to process this configMap. For staging set to false.
data:
  template: |
    {
        "declaration": {
            "c1-dc2-k-prod": {
                "Shared": {
                    "ingress_10_4_5_215_80": {
                        "policyFirewallEnforced": {
                            "bigip": "/Common/dc2_afm_policy_k8s_temp"
                        },
                        "snat": {
                            "bigip": "/Common/dc2_snat_k8s_1047"
                        },
                        "iRules": [
                            {
                                "bigip": "/Common/dc1_ltm_irule_new_media_uri_public_drop"
                            },
                            {
                                "bigip": "/Common/cos_irule_jira_uri_blocks"
                            }
                        ]
                    }
                }
            }
        }
    }